def mainVersion = "0.19.2"
def buildNumber = "1"

buildscript {
    repositories {
		maven { url = 'https://maven.minecraftforge.net' }
		jcenter()
		mavenCentral()
		maven { url 'https://maven.parchmentmc.org' }
	}
    dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
	}
}
apply plugin: 'net.minecraftforge.gradle.forge'
//Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.


version = "${mainVersion}-${buildNumber}"
group = "antibluequirk" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "alternatingflux"

sourceCompatibility = targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    mappings channel: 'parchment', version: version_parchment
}
repositories {
    maven {
    	name 'jared maven'
    	url 'http://blamejared.com/maven'
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${version_minecraft}-${version_forge}"
    implementation fg.deobf("blusunrize.immersiveengineering:ImmersiveEngineering:${version_ie}")
    datagenImplementation fg.deobf("blusunrize.immersiveengineering:ImmersiveEngineering:${version_ie}:datagen")
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
jar {
	manifest {
		attributes([
			"Specification-Title": "alternatingflux",
			"Specification-Vendor": "cosborn2",
			"Specification-Version": "1",
			"Implementation-Title": "Title",
			"Implementation-Version": "1.19.2",
			"Implementation-Vendor" :"cosborn2",
			"Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
	}
}
